### ISSUE TITLE
Mountain View Church of Christ Alto Can not add new information 

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/ChurchAppsSupport#1]
Mountain View Church of Christ Alto

Using Chums She Said loves it but as of last week she can not edit or add anything

Robin Simpson	[robinsimpson@calledtobehis.com](mailto:robinsimpson@calledtobehis.com)

**Comment by jzongker** [comment]
This was resolved and discussed on slack on July 1st.  Closing the old issue.
