### ISSUE TITLE
B1 Website hyperlink color/format

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/ChurchAppsSupport#109]
Ability to change the hyperlink color/format. 

More of a request as the user has a blue website and the links are blending in it would be nice to have the abilty to change that color. 

Conatact Naz kids if resolved

**Comment by jzongker** [comment]
I'll probably come up with a better styling solution later, but for now, this is achievable by adding an HTML block to the page and adding the CSS code to style the links however you like.  This example will make links white and underline in all the sections where they set the textColor to "light".

I'd suggest adding it a re-usable block like the site footer so it appears on every page.  Let me know if you need help getting it set up.

```
<style>
.sectionDark a { color: #FFFFFF; text-decoration:underline; }
</style>
```

**Comment by mbyrdLCS** [comment]
Yes I need help with this if you could make a short video I will try to follow it but I went in and tried and have no idea.

**Comment by jzongker** [comment]
Updated for FL Naz.

https://user-images.githubusercontent.com/1447203/224054790-8cbc6bfa-3885-42b9-9774-4c0dfb63861e.mp4

**Comment by mbyrdLCS** [comment]
Wow that is really cool

**Comment by Laaight** [comment]
Awesome!
