### ISSUE TITLE
Lock toolbar on WYSIWYG scroll

### ISSUE THREAD

**Issue by jzongker** [LiveChurchSolutions/ChurchAppsSupport#123]
When there's a lot of text the wysiwyg editor scrolls which is good, but the toolbar scrolls out of view.  We need to make just the content area inside the editor scroll.

![image](https://user-images.githubusercontent.com/1447203/226186961-ecaec7bf-0b3c-40a4-998a-5c5171bf6c71.png)

**Comment by Laaight** [comment]
@jzongker  I got a fix for this one. I made the toolbar to stick to the top but I just need to make one more adjustment to the CSS to stop it from overlapping. If you want to assign this one to me I can knock it out.
