### ISSUE TITLE
Lessons Subscribe button

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/ChurchAppsSupport#137]
We always get requests to be able to send the lessons with videos to the teachers we do not put it in the B1 app because we do not want them to cast the lessons. But it would be nice to have a [link like this one the one circled](https://lessons.church/classroom/tTEDg70QS5Z) That said Send this link to teachers so they can view the upcoming lesson. 
![Screen Shot 2023-03-30 at 5 24 53 PM](https://user-images.githubusercontent.com/65249159/228977679-ba656220-f314-436a-a427-39ceca9379a4.png)

**Comment by jzongker** [comment]
Can you clarify what exactly you're looking for?  Why not just send the https://lessons.church/classroom/tTEDg70QS5Z link to the teachers in addition to sending it to the parents?

**Comment by mbyrdLCS** [comment]
Because that link only shows last weeks lesson and lessons before that. Teachers want to watch the lessons ahead of time. However we don't want parents to have the ability to watch lessons ahead of time bc they may show it to the kids and then the kids will have already seen it when they get to class.

**Comment by jzongker** [comment]
Added the link.
