### ISSUE TITLE
Add auto redirect to /profile page

### ISSUE THREAD

**Issue by jzongker** [LiveChurchSolutions/ChurchAppsSupport#14]
Other apps redirect users to /login?auth=&redirectUrl=/profile but it doesn't actually redirect to the profile page after logging in.  Make it do so.

**Comment by gilbertmpanga12** [comment]
@jzongker is this what you meant?

https://user-images.githubusercontent.com/21340624/208669446-00409ffd-0fc5-4252-91c7-d8e32e09ba11.mov

**Comment by jzongker** [comment]
You actually found a second bug here that I went ahead and fixed.  We're in the process of consolidating several of the apps and StreamingLive was still pointing to an old accounts app here that no longer exists.  I've updated it to point to chums instead.

Other than that broken link, yes, you have the right idea.  That link will now take you to Chums as it should, but does not currently take you directly to the profile screen on chums.

**Comment by PhotoPaul** [comment]
@jzongker I may be missing something, but there seems to be a confusion organization-wide between using `returnUrl` (more common) and `redirectUrl` (less common).

The Login components already had a prop called `returnUrl`, so I added the code to make use of it. https://github.com/LiveChurchSolutions/ChumsApp/commit/8d0f12a464df7100455ad362fad3be78dc1544e2
For this to work moving forward, the redirection links should be consistently formed as `/login?returnUrl=/profile`
