### ISSUE TITLE
B1 Website Builder Permissions

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/ChurchAppsSupport#142]
In order to make pages you have to have edit content permission.  But this is not checked by default I think it needs to be.

<img width="1510" alt="Screen Shot 2023-04-08 at 6 47 55 AM" src="https://user-images.githubusercontent.com/65249159/230719606-928081bf-168c-4909-8287-1128229fd35a.png">

**Comment by Himali-Malvawala** [comment]
@mbyrdLCS that edit content permission for creating pages is set under Website Admins and not B1 Admins, which is checked by default.
![Screenshot 2023-04-20 110744](https://user-images.githubusercontent.com/86650000/233270800-75dcbea5-e2b0-47fb-8d82-08b7cd78d656.png)

**Comment by mbyrdLCS** [comment]
Got it thank you
