### ISSUE TITLE
Email Sent Option when form is completed 

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/ChurchAppsSupport#147]
Is there an option or a way to set up an email that goes out every time a form is submitted? 

We have a contact form set up here https://fellowshipregional.b1.church/getconnected 

But the only way to see if it has a submission is to go into chums and look can we send it to the email that set the form up?

**Comment by Himali-Malvawala** [comment]
#152

**Comment by Himali-Malvawala** [comment]
https://github.com/LiveChurchSolutions/ChurchAppsSupport/issues/152

**Comment by Himali-Malvawala** [comment]
Email toggle option #152
