### ISSUE TITLE
B1 App Pages are not working

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/ChurchAppsSupport#149]
YOu can make a page for the app and select it however when you go and open up that page on the app it is always blank not showing what you put on that page. I found this out when working on Fellowship Regional Church

![Screen Shot 2023-04-18 at 4 36 52 PM](https://user-images.githubusercontent.com/65249159/232910859-f7d8551c-ea8a-4cc9-8e78-1d5f2f7ac89b.png)

**Comment by jzongker** [comment]
You're screenshot shows the mobile pages which show up at /member .  If you want to add a web page for the public site, click that third icon on the left nav bar.

**Comment by mbyrdLCS** [comment]
Even after Logging in the page is still blank

**Comment by jzongker** [comment]
This is a B1Mobile app issue.  You can test with "Fellowship Regional Church" in the production environment.  This url should be getting framed in on the mobile app.  https://fellowshipregional.b1.church/member/page-name

**Comment by jzongker** [comment]
Fixed with https://github.com/LiveChurchSolutions/B1Mobile/commit/81643212b4675cb04819b82800db8b169328c0a8
