### ISSUE TITLE
B1 Website Text section not adding correctly

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/ChurchAppsSupport#173]
https://github.com/LiveChurchSolutions/ChurchAppsSupport/assets/65249159/24f71f61-5f50-4ba3-8aeb-304646b3743f

**Comment by jzongker** [comment]
Fixed by @Himali-Malvawala 
"Turns out whenever there was a change in element, that DroppableArea below the element was not updating and kept showing the value it had when page was first loaded."
