### ISSUE TITLE
Stock photos are masked to the wrong size

### ISSUE THREAD

**Issue by tbyrd77** [LiveChurchSolutions/ChurchAppsSupport#174]
![setting up stock photos](https://github.com/LiveChurchSolutions/ChurchAppsSupport/assets/127863068/2a6f67aa-3b45-4685-9991-e4f0eb6d276f)

**Comment by Himali-Malvawala** [comment]
@tbyrd77 Can you please elaborate more on this?

**Comment by Himali-Malvawala** [comment]
Oh, okay. I'll look into it.

**Comment by jzongker** [comment]
@Himali-Malvawala I think we can remove the aspect ratio requirement from section backgrounds.

**Comment by Himali-Malvawala** [comment]
Done!
