### ISSUE TITLE
Donate - Include link to change recurring subscriptions in receipt

### ISSUE THREAD

**Issue by jzongker** [LiveChurchSolutions/ChurchAppsSupport#179]
When a user receives the confirmation receipt for a recurring donation, we should include a link to modify that subscription.

https://[subdomain].b1.church/member/donate

**Comment by jzongker** [comment]
Can you update the link so it pulls from the environment settings?  On staging it'll send you to [sub].b1.church instead of [sub].staging.b1.church.  Otherwise it looks good

**Comment by Himali-Malvawala** [comment]
Done!
