### ISSUE TITLE
Colanders will not allow you to add events 

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/ChurchAppsSupport#181]
Colanders will not allow you to add events 

It says you need a group I have a group still it will not let me add an event 

<img width="1498" alt="Screen Shot 2023-08-17 at 4 22 54 PM" src="https://github.com/LiveChurchSolutions/ChurchAppsSupport/assets/65249159/754a51e7-9405-45b5-ac6d-3bbe4c36f905">

**Comment by Himali-Malvawala** [comment]
@mbyrdLCS Are you a member of that group? Only if you are a member, you'll be able to see those groups in the groups-tab.

![image](https://github.com/LiveChurchSolutions/ChurchAppsSupport/assets/86650000/c4eef18d-48ee-4440-8f7a-80ba9b9c130e)

**Comment by mbyrdLCS** [comment]
I am not sure What I am doing wrong. 
<img width="1505" alt="Screen Shot 2023-08-21 at 1 37 01 PM" src="https://github.com/LiveChurchSolutions/ChurchAppsSupport/assets/65249159/150e475e-c945-49f7-8106-469b0fc662ff">
<img width="1505" alt="Screen Shot 2023-08-21 at 1 37 22 PM" src="https://github.com/LiveChurchSolutions/ChurchAppsSupport/assets/65249159/3c13a99c-7953-4cb4-a572-563bedb41042">

**Comment by Himali-Malvawala** [comment]
I see that at both the places (B1 and Chums), you are signed in as 'Mike Byrd' and you've added 'Micheal Byrd' as a group member. Those are two different people I guess. Can you add 'Mike Byrd' as a group member?

**Comment by Himali-Malvawala** [comment]
Awesome!

Yeah, once you hit save, you'll see that group listed. But it looks like the group doesn't have any events, so that's why the events and groups are not getting listed. But that shouldn't be the case, groups should always get listed even though it has no events.

So, I've fixed that and once the changes are pushed, it'll work.

**Comment by Himali-Malvawala** [comment]
Done!
