### ISSUE TITLE
Needing to show somewhere that once you set up a live stream there is a page that shows that stream.

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/ChurchAppsSupport#189]
Somewhere on this page 

<img width="1505" alt="Screen Shot 2023-08-23 at 10 47 23 AM" src="https://github.com/LiveChurchSolutions/ChurchAppsSupport/assets/65249159/49f10cde-e243-4977-af42-579b7c1ed5e1">

**Comment by jzongker** [comment]
How about adding a "View Your Stream" link to external resources that links to /stream ?

**Comment by mbyrdLCS** [comment]
Yep that would be perfect

**Comment by Himali-Malvawala** [comment]
Added.
