### ISSUE TITLE
Donate - New Donations Not Showing Up in B1

### ISSUE THREAD

**Issue by jzongker** [LiveChurchSolutions/ChurchAppsSupport#192]
I made several test donations today, but the last donation logged in the second box is from 2021.  Need to track down what's going on.

![image](https://github.com/LiveChurchSolutions/ChurchAppsSupport/assets/1447203/5ac66b40-02de-46a4-b769-69e0f0e578d1)

**Comment by Himali-Malvawala** [comment]
It was because the webhook was not listening properly. Re-setting the webhook worked!
