### ISSUE TITLE
Donate - Recurring Email Tweaks

### ISSUE THREAD

**Issue by jzongker** [LiveChurchSolutions/ChurchAppsSupport#196]
Below is the current recurring donation email.  There are two changes I think we need.

1. Just add the word "recurring" to "Your recurring donation has been confirmed!"
2. Include the start date.  I future dated this one and it could make someone nervous if they think it's going through today.

![image](https://github.com/LiveChurchSolutions/ChurchAppsSupport/assets/1447203/ee685db7-3aee-44e8-aa5f-b356b64aae18)

**Comment by Himali-Malvawala** [comment]
Done!
