### ISSUE TITLE
Make facebook live work with live stream

### ISSUE THREAD

**Issue by tbyrd77** [LiveChurchSolutions/ChurchAppsSupport#197]
I have tried several times to get facebook live to work with our livestream app. I am not sure if I am entering the wrong ID code or what. I may be missing something. Thanks for the help.
<img width="963" alt="Screen Shot 2023-08-28 at 12 21 52 PM" src="https://github.com/LiveChurchSolutions/ChurchAppsSupport/assets/127863068/66fc7b5b-2b92-42cf-a3af-9b4b90020493">

**Comment by jzongker** [comment]
With Facebook there isn't a permanent live url you can plug in (that I know of).  It's a different url for each service and you have to create a new Sermon each week within B1.  To get the url, go to the page with the video on Facebook, click the 3 dots in the corner and choose copy link.

![image](https://github.com/LiveChurchSolutions/ChurchAppsSupport/assets/1447203/edcba3b2-2288-4def-bde2-d039b342f490)

That will give you an address like the one in the photo, and at the end is the ID of the video.  Plug in that ID in the sermon settings and it'll work.

![image](https://github.com/LiveChurchSolutions/ChurchAppsSupport/assets/1447203/2eb8f599-c0c8-4a92-aff3-1e202fe291e3)
