### ISSUE TITLE
B1 Website Design can not delete Navigation

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/ChurchAppsSupport#209]
<img width="1479" alt="Screenshot 2023-09-07 at 8 00 39 AM" src="https://github.com/LiveChurchSolutions/ChurchAppsSupport/assets/65249159/712bdfc3-2055-40ea-9beb-66383f00dd22">

**Comment by Himali-Malvawala** [comment]
Fixed.
