### ISSUE TITLE
Admin Page I can not add anyone

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/ChurchAppsSupport#3]
Trying to add myself to Lake City So can I test issues. When I search my name to add myself and hit search nothing comes up. I think it should ask to add a new person. 
<img width="1485" alt="Screen Shot 2022-07-16 at 6 50 01 AM" src="https://user-images.githubusercontent.com/65249159/179351974-21b9099c-3f0f-4881-a438-8cd40cbeb9f7.png">

**Comment by jzongker** [comment]
I believe we determined this was a permissions issue and corrected it a couple of weeks ago.  Closing the issue.  Let me know if you still have any problems.
