### ISSUE TITLE
Lessons.Church App bad link in Subscribe

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/ChurchAppsSupport#32]
I think after the update this link needs to be fixed
![Screen Shot 2022-12-04 at 10 07 44 AM](https://user-images.githubusercontent.com/65249159/205502029-7b3062c7-9ccf-48f7-b0a6-a873c6cf8421.png)

**Comment by mbyrdLCS** [comment]
Currently it goes to https://accounts.churchapps.org/

**Comment by pranavmalvawala** [comment]
Fixed here - https://github.com/LiveChurchSolutions/LessonsApp/commit/9fdb712b8dad357e082ac8f03fcca4c4025716bc
