### ISSUE TITLE
Recurring gifts do not produce receipts 

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/ChurchAppsSupport#36]
I set up a bank payment here https://livecs.b1.church/donate 

I did one one-time gift and got a receipt with no issue 

Then I set up a monthly and I did not get a receipt also when I looked in stripe it did not generate a receipt their either

**Comment by jzongker** [comment]
Was the card/bank actually charged in Stripe?

**Comment by mbyrdLCS** [comment]
Yes it was

**Comment by mbyrdLCS** [comment]
Payments have now been processed and no receipt was send for first time recurring gift

**Comment by jzongker** [comment]
I'm thinking maybe just send a "Thank you" email at the time the recurring donation is initially scheduled, confirming what has been scheduled?  Even if the bank validation hasn't occurred yet.

I don't think we should email people every month when their donations actually go through.

Thank sound good @mbyrdLCS ?

**Comment by mbyrdLCS** [comment]
Yes that works great just gives confidence what you just set up worked.
