### ISSUE TITLE
Web App not allowing Member login to see directory

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/ChurchAppsSupport#39]
Video of login working on a browser 

https://user-images.githubusercontent.com/65249159/207420312-9232f1b0-1b0e-47cb-81f9-47fdd8bab49e.mp4

Video of login not working on the B1 App

https://user-images.githubusercontent.com/65249159/207420396-99fb66d1-1ee0-497e-ada8-347d3fce24ce.mp4

**Comment by jzongker** [comment]
This was a bug due to the MembershipApi/AccessApi consolidation that has been fixed now.
