### ISSUE TITLE
Avatars in header should be round

### ISSUE THREAD

**Issue by jzongker** [LiveChurchSolutions/ChurchAppsSupport#41]
We're currently getting a rectangular avatar within a circle.  Update the code so the avatar fills the circle.

![image](https://user-images.githubusercontent.com/1447203/208807368-351f17d4-4c8a-40d0-ba99-acb4f90eb3c9.png)

This is in /appBase/material/UserMenu.tsx in all of the web projects.

**Comment by PhotoPaul** [comment]
Fixed [1d9498fcda11f156eb42b04117450ddc79c1b9cb](https://github.com/LiveChurchSolutions/AppBase/commit/1d9498fcda11f156eb42b04117450ddc79c1b9cb)
