### ISSUE TITLE
Lessons.church Print function

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/ChurchAppsSupport#46]
When I click on the print, it only prints the open headings (I attached a pdf of the printout) instead of printing out the entire script. When I go to where I can edit the script/schedule, I can print out that larger section but it doesn’t have the entire script on it. there should be a way to be able to print out the entire script/schedule with all of the tabs opened. When I open a different one.

[unnamed document.pdf](https://github.com/LiveChurchSolutions/ChurchAppsSupport/files/10322412/unnamed.document.pdf)

When resolved I will let andrew.peterman25@gmail.com know

**Comment by jzongker** [comment]
Closed by @GhaffarMuhammad78600
