### ISSUE TITLE
Lessons.church Video preview 

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/ChurchAppsSupport#47]
We are needing the preview video for the lessons to work with youtube and now vimeo when I enter a vimeo link it is not working. 

<img width="1507" alt="Screen Shot 2022-12-31 at 5 20 37 PM" src="https://user-images.githubusercontent.com/65249159/210157502-961cbf4f-536b-4180-a145-65c48f8c9ac2.png">
<img width="1507" alt="Screen Shot 2022-12-31 at 5 20 53 PM" src="https://user-images.githubusercontent.com/65249159/210157504-76948dc0-8155-4cff-8d31-53ace60a516e.png">

**Comment by jzongker** [comment]
To get the embeddable url from https://vimeo.com/748024140 click on Share->Embed and copy the url from the iframe which is https://player.vimeo.com/video/748024140?h=14a2020af3 in this case.
