### ISSUE TITLE
double URL in settings

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/ChurchAppsSupport#48]
I found the following:
When at the below screen (https://app.chums.org/settings , I select an edit field, then select import/export the double URL is displayed.
 
https://app.chums.org/settings/https://transfer.chums.org/

![image001](https://user-images.githubusercontent.com/65249159/211304279-35aa7cac-48b1-41f6-86aa-af1f82b9b945.png)

When fixed Micheal will notify 
Forrest Carleton
[fcarleton@gmail.com](mailto:fcarleton@gmail.com)

Also
john.kofroth@outlook.com

**Comment by jzongker** [comment]
This ended up being urgent so Pranav took care of it at Micheal's request.
