### ISSUE TITLE
https://livecs.org/solutions missing trailing #

### ISSUE THREAD

**Issue by fcarleton** [LiveChurchSolutions/ChurchAppsSupport#49]
From the https://livecs.org/solutions URL, selecting the [Solution] Command push button (CPB) the trailing # is not appended.  It is displayed in the lower left corner.

If the trailing # is manually appended the correct screen is displayed.
![image](https://user-images.githubusercontent.com/39572391/211315405-d71877d2-ef68-4018-952d-530dc98270b3.png)

I tried to attach a print screen.

**Comment by fcarleton** [comment]
Is there a system test plan?

**Comment by pranavmalvawala** [comment]
You mean on clicking the link the pages should start from the top right? 

What do you mean by system test plan?

**Comment by jzongker** [comment]
Thanks @fcarleton .  I may be misunderstanding the issue, but I believe the bigger problem is the Contact button doesn't really go anywhere.  I've updated it to be an email to support@livecs.org.
