### ISSUE TITLE
Cell Phone 

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/ChurchAppsSupport#50]
Is there a way to add a cell phone instead of just work and home? 

Or am I missing a way this can be done in admin?

<img width="1507" alt="Screen Shot 2023-01-09 at 5 20 12 PM" src="https://user-images.githubusercontent.com/65249159/211420063-87461c9e-c90f-42b3-b2a8-105b7786384a.png">

If we do ad the option micheal will email john.kofroth@outlook.com Who requested it

**Comment by PhotoPaul** [comment]
@mbyrdLCS This should be fixed as soon as this commit passes the tests https://github.com/LiveChurchSolutions/ChumsApp/commit/61eb93ada31f681361b692c85bebb0ddd3a25a7e
