### ISSUE TITLE
Wrong lesson being scheduled on Lessons.church

### ISSUE THREAD

**Issue by jzongker** [LiveChurchSolutions/ChurchAppsSupport#54]
When scheduling a lesson, if you change the Lesson, but accept the first option in the list for the Venue, the VenueId never gets updated and the VenueId stored belongs to the previously selected lesson.

Need to add a useEffect I think to set the venueId to the first venue in the dropdown after loadVenues().

![image](https://user-images.githubusercontent.com/1447203/211690965-02fccdb5-7a48-4cfc-9994-30e89360cf14.png)

**Comment by GhaffarMuhammad78600** [comment]
@jzongker please test this issue on staging.its working fine .and this issue is not regenerate on staging with many tries.so please check it if still you face this issue please share a loop vedio.

https://www.loom.com/share/6ab21e6373a546ba8a678126a642bdc7

**Comment by jzongker** [comment]
Confirmed this is issue is not currently reproducible.  Closing for now.  Re-open if them problem recurs.
