### ISSUE TITLE
What size do we need the logo to be 

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/ChurchAppsSupport#55]
It is extremely hard to get a logo that fits in the space can we make it auto-resize or put what dimensions we should use? 

Included is a logo I was trying to make work and could not get it to work

<img width="1507" alt="Screen Shot 2023-01-13 at 4 49 24 PM" src="https://user-images.githubusercontent.com/65249159/212425847-b6ed8a7e-566a-4e47-b008-9a5c8c01b157.png">
![modified logo rectangular](https://user-images.githubusercontent.com/65249159/212425892-329522c0-8fee-440a-9d3a-f5bccf9f30b1.jpg)
![modified logo rectangular](https://user-images.githubusercontent.com/65249159/212425896-b649f3b0-4735-46a7-a8d9-a808f7210667.png)

**Comment by jzongker** [comment]
The aspect ratio is 4:1.  You should get a cropper tool like this.  
![image](https://user-images.githubusercontent.com/1447203/212447395-5b8326c6-ee6f-4adc-9eb8-ad3407d96b26.png)

I think it's going to look better on most sites if you get rid of the slogan and just use the round logo with a transparent background.

**Comment by mbyrdLCS** [comment]
Once I knew it needed to be 4:1 / 1280 X 320 It was simple to resize and make a logo fit. would it be possible to put that in the text?

**Comment by PhotoPaul** [comment]
The recommended dimensions were added https://github.com/LiveChurchSolutions/ChumsApp/commit/34c3d216c242f66c46b52aedc7bb5af454e41fae
