### ISSUE TITLE
Not able to add new Groups 

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/ChurchAppsSupport#56]
I am trying to add groups for check-ins and it allows me to add a group but they are not showing up after I add them. 

https://user-images.githubusercontent.com/65249159/212892737-af71111c-1715-45dd-86bb-be7c62b66da8.mp4

**Comment by PhotoPaul** [comment]
I'm not sure when it is going to go live, but I pushed a fix https://github.com/LiveChurchSolutions/MembershipApi/commit/ec7041e136dadc8bfaf097a4506d6a98ad70589c
