### ISSUE TITLE
Credit card number smashed 

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/ChurchAppsSupport#61]
In the b1 app when entering a cc on a mobile device it does not look correct after it is entered. 

![IMG_7384](https://user-images.githubusercontent.com/65249159/213268846-6e5dd596-f5eb-482d-8ffa-fee0c5b830a2.PNG)

**Comment by PhotoPaul** [comment]
@mbyrdLCS  Do you remember the exact device/model this happened on? I tested on a few different device emulators, and I failed to replicate this issue. (Could it be that they had some kind of accessibility setting enabled that zoomed in the UI further than it should?)

**Comment by mbyrdLCS** [comment]
the Above Pic was an Android I am able to replicate it with my iPhone. 
![IMG_7385](https://user-images.githubusercontent.com/65249159/213696655-c8345ef4-79b2-4569-94ef-16463969ae53.PNG)

**Comment by jzongker** [comment]
I believe this has been resolved.  @mbyrdLCS can you confirm when you have time?  This is what I see at https://livecs.b1.church/member/donate

https://user-images.githubusercontent.com/1447203/216109029-d9de5759-8431-426a-a19f-a28183e35c65.mp4

**Comment by mbyrdLCS** [comment]
Confirmed Looks good thanks!!
