### ISSUE TITLE
First time sign in when on mobile

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/ChurchAppsSupport#62]
When you are signing in you have to select a church this is what it looks like on an iPhone using safari.

 
![IMG_7400](https://user-images.githubusercontent.com/65249159/213584879-8888718e-c7c1-4b16-963d-2e372e703cfa.PNG)

**Comment by PhotoPaul** [comment]
@mbyrdLCS 
https://github.com/LiveChurchSolutions/AppBase/compare/d011c1f076c3ec937fb51280ed3ff298b7cfbcd0...79e9b9923e9d0f5b2f6b5fc0d4aefe29e03dedbd#diff-8941b6830898b9b51aa3d397607dae95c90b717e67409ae5c469fc85dae09ca0
https://user-images.githubusercontent.com/3471804/213663682-bd6441ce-0343-4aba-8336-a58035f2db24.mp4

**Comment by PhotoPaul** [comment]
@mbyrdLCS  I pushed this fix: https://github.com/LiveChurchSolutions/AppBase/compare/d011c1f076c3ec937fb51280ed3ff298b7cfbcd0...79e9b9923e9d0f5b2f6b5fc0d4aefe29e03dedbd#diff-8941b6830898b9b51aa3d397607dae95c90b717e67409ae5c469fc85dae09ca0

It should now work like this:

[![Video title](https://img.youtube.com/vi/VIDEO_ID/0.jpg)](https://user-images.githubusercontent.com/3471804/213663682-bd6441ce-0343-4aba-8336-a58035f2db24.mp4)

**Comment by jzongker** [comment]
Thanks @PhotoPaul .  Closing this issue
