### ISSUE TITLE
recurring donations

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/ChurchAppsSupport#64]
When Setting up a recurring donation it is charging the day of the donation and not the date that is set to start the recurring donations.  I recently set this up and I know I set it for the first but it charged the day of. 

<img width="1382" alt="Screen Shot 2023-01-20 at 9 16 24 AM" src="https://user-images.githubusercontent.com/65249159/213756216-568d82ae-3d15-46ee-9a1f-51d49a7f8eef.png">

**Comment by jzongker** [comment]
This screen is available at https://ironwood.staging.b1.church/member/donate when logged in with any account.

**Comment by jzongker** [comment]
Fixed with https://github.com/LiveChurchSolutions/GivingApi/commit/5e64a06e02a01a5ff7ccedcdbde3ab790797305b
