### ISSUE TITLE
B1 App Checkins causing it to not work

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/ChurchAppsSupport#70]
![IMG_7464](https://user-images.githubusercontent.com/65249159/215219352-9afc5aac-84ec-4378-8dc3-e376c71d462e.PNG)

![IMG_7465](https://user-images.githubusercontent.com/65249159/215219167-0feb07b4-3ee2-4f28-871c-a9e7496fce3a.PNG)

**Comment by jzongker** [comment]
@shahiddev10 This is with Lake City Christian Church on production.  Could you please test this and fix if necessary.

**Comment by jzongker** [comment]
![Screenshot_20230220-100624](https://user-images.githubusercontent.com/1447203/220154983-22afebbc-180d-4cab-a6e7-59748f59170e.png)
This is working correctly now.  I believe it was a config issue previously.

**Comment by jzongker** [comment]
It appears to be hanging on the next screen after you click on a service.

**Comment by jzongker** [comment]
Fixed with https://github.com/LiveChurchSolutions/B1Mobile/pull/51
