### ISSUE TITLE
B1 App

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/ChurchAppsSupport#71]
The Forgot my password does not work within the app. Rather there is just no field to enter your email. 

![IMG_7542](https://user-images.githubusercontent.com/65249159/216852534-36ff86ab-a82a-4861-8acf-48137bfebc4f.jpg)

![IMG_7543](https://user-images.githubusercontent.com/65249159/216852542-30ba6270-4df2-4e42-9e14-54589eefba0e.jpg)

**Comment by jzongker** [comment]
This is a problem with the web app B1App rather than the B1Mobile native app.
This url is returning blank.   Need to determine why and fix it.
https://ironwood.b1.church/login?action=forgot
https://{anysubdomain}.b1.church/login?action=forgot

**Comment by jzongker** [comment]
https://ironwood.b1.church/login?action=register is also broken.

**Comment by jzongker** [comment]
Fixed with https://github.com/LiveChurchSolutions/AppBase/commit/e155947010010d505404c5c964b0a952095158c7
