### ISSUE TITLE
Website Misspelling 

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/ChurchAppsSupport#72]
Chums.org 
breakdowns is not spelled correctly it is at the bottom of the page
<img width="1512" alt="Screen Shot 2023-02-08 at 1 46 08 PM" src="https://user-images.githubusercontent.com/65249159/217623615-1b33b2d7-8d77-4752-bd92-581f474c5970.png">

**Comment by hamzasiddiqi2168** [comment]
done
