### ISSUE TITLE
Say Function not clearing after a save

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/ChurchAppsSupport#73]
Below is a video I did confirm this is an issue that I can repeat.

**Comment by jzongker** [comment]
It looks like the video didn't upload.  Can you try again?

**Comment by mbyrdLCS** [comment]
https://user-images.githubusercontent.com/65249159/217979617-0ef0f99d-e724-42ae-a98c-3dc70d7c504a.mp4

**Comment by jzongker** [comment]
Fixed via https://github.com/LiveChurchSolutions/LessonsApp/pull/239
