### ISSUE TITLE
PageAdmin: Dropping New Section on Bottom of Page is Hard

### ISSUE THREAD

**Issue by jzongker** [LiveChurchSolutions/ChurchAppsSupport#76]
Dragging a new section to the very bottom of the page is difficult because you have to hold it there until the div scrolls down.  We need to find a way to fix that.  Maybe just add a DroppableArea outside of the scrolling div at the bottom of the DisplayBox and dropping it there will also slot it in the right spot?
![image](https://user-images.githubusercontent.com/1447203/218343626-524ad69d-0f06-425a-ba5f-5a05906a0349.png)

**Comment by pranavmalvawala** [comment]
Adding DroppableArea outside of scrolling div confuses things in my opinion. What the usual approach, I think should be scroll before you add, that way the place you wanna add component to is always in view. What do you think?

**Comment by jzongker** [comment]
Autoscroll to the bottom would fix the issue for those who want to add it to the bottom of the page, but it would be very annoying in most other scenarios where the user is currently scrolled to the part of the page they wish to add the section to.

I don't think it would be too confusing if this green plus just appeared below the scroll bar instead of within the scrollable area.
![image](https://user-images.githubusercontent.com/1447203/218375823-decf1151-95ff-4f55-8273-476953682235.png)

**Comment by pranavmalvawala** [comment]
Sure! we can give this a shot
