### ISSUE TITLE
Chums logs out when moving to the import export tool

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/ChurchAppsSupport#80]
When you go to the import tool in chums you have to log in again to use the tool it would be nice to have it auto login in
<img width="1559" alt="Screen Shot 2023-02-14 at 6 28 38 PM" src="https://user-images.githubusercontent.com/65249159/219208953-d12023b3-b00f-4a6d-a699-f5144cc0d0a9.png">
current workaround
<img width="1512" alt="Screen Shot 2023-02-14 at 6 31 25 PM" src="https://user-images.githubusercontent.com/65249159/219209091-f9cac09e-5bb7-4f2a-b221-7b0c22336a43.png">

**Comment by jzongker** [comment]
Fixed by https://github.com/LiveChurchSolutions/ChumsApp/pull/224
