### ISSUE TITLE
Website glitch on the Card function

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/ChurchAppsSupport#81]
You can not scroll down and hit save after entering the info. 

<img width="1512" alt="Screen Shot 2023-02-15 at 6 08 57 PM" src="https://user-images.githubusercontent.com/65249159/219211432-66fab4cf-7fb8-4250-a9c5-d57d9c41d3fb.png">

**Comment by jzongker** [comment]
I believe #79 and #110 will address this.  Let's check again once they are resolved.
