### ISSUE TITLE
B1 App redirect to Donate is not loading

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/ChurchAppsSupport#82]
This could be across the board I just found it in the B1 App https://livecs.b1.church/donate does not load. 

![IMG_7639](https://user-images.githubusercontent.com/65249159/219378902-48a28de0-c20d-4d47-ba0a-a0ad0a9a700f.PNG)

**Comment by jzongker** [comment]
This was fixed with the app store deploy last week.
