### ISSUE TITLE
Chums import export tool

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/ChurchAppsSupport#84]
Trying to use the import export tool to bring data in from a .csv even when I download the sample and try to upload it into chums it does not work. 

https://transfer.chums.org/

Breeze import is working great.

**Comment by mbyrdLCS** [comment]
Hey, Jim yes there is an import tool but right now we are having issues with the tool. As soon as we get it back up and running I will make a tutorial and send it to you. 

Thanks, 
Micheal Byrd 

On Mar 9, 2023, at 7:20 PM, Jim Cormode <jim.cormode@cummingschristianchurch.com> wrote:

Is it possible to import data to CHUMS from Excel?

-- 
Jim Cormode
Cummings Christian Church

**Comment by jzongker** [comment]
It appears to be working on staging.  If there are still errors, it's likely either failure to log in first or a permissions issue.  If it recurs, please take a video of the process and then a screenshot of the Chome Inspector output.

https://user-images.githubusercontent.com/1447203/224771790-5d8d93d5-f087-4390-9c9e-2fcef25d29c8.mp4

**Comment by jzongker** [comment]
The issue was a combination of a space in the filename "people .csv" and the files not being in the root of the zip file, but rather in a folder.  A tutorial is being made to help address this.
